FROM node:12-alpine as base

ENV APP_HOME=/usr/src/app
ENV HOST_HOME=./packages/blog_frontend

WORKDIR $APP_HOME

EXPOSE ${BLOG_FRONTEND_APP_EXPOSED_PORT:-3000}

COPY package.json yarn.lock ./

RUN yarn install && yarn global add react-scripts@3.4.3

COPY $HOST_HOME .

FROM base as dev
ENV NODE_ENV=development

RUN chmod +x init.sh

CMD /bin/sh ./init.sh
