FROM node:12-alpine as base

ENV APP_HOME=/usr/src/app
ENV HOST_HOME=./packages/blog_api

WORKDIR $APP_HOME

EXPOSE ${BLOG_API_APP_EXPOSED_PORT:-3001}

COPY package.json yarn.lock ./

RUN yarn config set workspaces-experimental true && yarn install --silent

COPY $HOST_HOME .

FROM base as dev
ENV NODE_ENV=development

RUN chmod +x init.sh

CMD /bin/sh ./init.sh
